### ISSUE TITLE
Controlled affiliation sometimes false: Brno vs. Bern

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#734] opened 2021-12-09 18:24 UTC
**Describe the issue**
Sometimes, the controlled affiliation is wrong.

The fuzzy matching identifies the wrong institution:

**To Reproduce**
1. save a document with the following author affiliation: *Department of Biology, Masaryk University, Brno, Czech Republic - International Clinical Research Center, St. Anne’s University Hospital, Brno, Czech Republic*
2. it is recognised as University of Bern, see below

List of examples:
* Masaryk University, Brno > University of Bern
* Université de Lucerne > CERN

Score of the fuzzy matching:
```txt
Uni of Bern and Hospital [58]
Hôpital de l'Ile [50]
Inselspital [55]
Università di Berna [65]
Universität Bern [81]
Universitätsspital Bern [78]
Université de Berne [68]
University Hospital Bern [96]
University Hospital Berne [92]
University of Bern [78]
University of Berne [74]
bern university hospital [79]
university hospital of bern [74]
university hospitals of bern [71]
```

**Expected behavior**
The controlled affiliation is smarter. The example above is not recognised as University of Bern.

**Screenshots**
![image](https://user-images.githubusercontent.com/8154915/145453658-f5f4cf4e-5e9f-469a-934e-f07cfe4d057f.png)

**Comment by PascalRepond** [comment] 2023-04-04 06:43
Duplicate of https://github.com/rero/sonar/issues/824

**Closed by PascalRepond** 2023-04-04 06:43 UTC
Labels: bug, p-Low
